baseURL = 'https://ttn-lab.github.io/'
copyright = "© TTN Lab"
enablerobotstxt = true
languageCode = 'en-us'
timeZone = 'Europe/Madrid'

[languages.en]
title = "TTN Lab"
weight = 10

[[module.imports]]
path = 'github.com/willfaught/paige'

[params.paige]
style = "#paige-content > * { margin-left: auto; margin-right: auto; max-width: 40rem; }"
color = '#cb2c30'
keyword_style = 'pills'

[params.paige.comments]
disable = true

[params.paige.search]
hide_page = false
